name = "SEIR"
uuid = "32d6000a-511b-47d2-815b-11ce148b4698"
authors = ["Adam H. Sparks <adamhsparks@gmail.com> and contributors"]
version = "0.1.0"

[deps]
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
RCall = "0.13"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
